---
- name: Create monitoring group
  group:
    name: "{{ monitoring_group }}"
    system: yes

- name: Create monitoring user
  user:
    name: "{{ monitoring_user }}"
    group: "{{ monitoring_group }}"
    system: yes
    home: "{{ monitoring_user_home }}"
    shell: /sbin/nologin

- name: Grant monitoring user access to the PostgreSQL
  become_user: postgres
  postgresql_user:
    name: "{{ monitoring_user }}"
    password: "{{ monitoring_postgresql_password }}"

- name: Create configured Postgres monitoring container
  docker_container:
    name: monitoring_postgres_exporter
    image: genialis/postgres_exporter:0.8.0
    pull: yes
    published_ports: "9187:9187"
    network_mode: "host"
    env:
      DATA_SOURCE_NAME: >-
        {{
          'postgresql://%s:%s@%s:%s/%s?sslmode=disable' | format(
            monitoring_postgresql_user,
            monitoring_postgresql_password,
            monitoring_postgresql_host,
            monitoring_postgresql_port,
            monitoring_postgresql_db_name
          )
        }}
    memory: "256m"
    memory_swap: "256m"

- name: Enable systemd units for controlling each monitoring container
  service:
    name: monitoring-container@postgres_exporter
    enabled: yes
